package kvs.core.fileformat.kvsml;

import java.io.File;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.FloatBuffer;
import java.nio.IntBuffer;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;

import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.xml.sax.SAXException;

import kvs.core.KVSException;
import kvs.core.fileformat.FileFormatBase;
import kvs.core.fileformat.kvsml.TagParser.WritingDataType;

public class KVSMLObjectLine extends FileFormatBase {


    private static final long serialVersionUID = 7968546184003094081L;
    protected WritingDataType m_writing_type; // /< writing data type
    protected String m_line_type; // /< line type
    protected String m_color_type; // /< line color type
    protected FloatBuffer m_coords; // /< coordinate array
    protected IntBuffer m_connections; // /< connection array
    protected ByteBuffer m_colors; // /< color (r,g,b) array
    protected FloatBuffer m_sizes; // /< size array

    public KVSMLObjectLine() {
        super();
        m_writing_type = WritingDataType.Ascii;
    }

    public KVSMLObjectLine( File filename ) throws KVSException {
        super();
        m_writing_type = WritingDataType.Ascii;
        this.read( filename );
    }

    public String lineType() {
        return m_line_type;
    }

    public String colorType() {
        return m_color_type;
    }

    public FloatBuffer coords() {
        return m_coords;
    }

    public ByteBuffer colors() {
        return m_colors;
    }

    public IntBuffer connections() {
        return m_connections;
    }

    public FloatBuffer sizes() {
        return m_sizes;
    }

    public void setWritingDataType( WritingDataType writing_type ) {
        m_writing_type = writing_type;
    }

    public void setLineType( String line_type ) {
        m_line_type = line_type;
    }

    public void setColorType( String color_type ) {
        m_color_type = color_type;
    }

    public void setCoords( FloatBuffer coords ) {
        m_coords = coords;
    }

    public void setColors( ByteBuffer colors ) {
        m_colors = colors;
    }

    public void setConnections( IntBuffer connections ) {
        m_connections = connections;
    }

    public void setSizes( FloatBuffer sizes ) {
        m_sizes = sizes;
    }

    public static boolean check( File filename )
    {
        try {
            DocumentBuilderFactory dbfactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder builder = dbfactory.newDocumentBuilder();
            Document document = builder.parse( filename );
            return  LineObjectParser.check( document );
        } catch (SAXException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
        catch (ParserConfigurationException e) {
            e.printStackTrace();
        }
        return( false );
    }

    @Override
    public void read( File filename ) throws KVSException {
        m_filename = filename;

        try{

            DocumentBuilderFactory dbfactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder builder = dbfactory.newDocumentBuilder();
            Document document = builder.parse( filename );

            LineObjectParser parser =new LineObjectParser();
            parser.parse( document );

            m_line_type  = parser.lineType();
            m_color_type = parser.colorType();

            m_coords = parser.setCoordsTo();
            m_colors = parser.setColorsTo();
            m_connections = parser.setConnectionsTo();
            m_sizes = parser.setSizesTo();

        } catch (SAXException e) {
            e.printStackTrace();
            throw new KVSException("Xml parse failured");
        } catch (IOException e) {
            e.printStackTrace();
            throw new KVSException("Read failured");
        } catch (ParserConfigurationException e) {
            e.printStackTrace();
            throw new KVSException("Create DocumentBuilder failured");
        }

    }

    @Override
    public void write( File filename ) throws KVSException {
        m_filename = filename;

        try{

            DocumentBuilderFactory dbfactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder builder = dbfactory.newDocumentBuilder();

            Document doc = builder.newDocument();

            doc.setXmlVersion( "1.0" );
            doc.createComment( " Generated by kvs.KVSMLObjectLine.write() " );

            // <KVSML>
            Element kvs_node = doc.createElement( "KVSML" );
            doc.appendChild( kvs_node );

            // <Object type="LineObject">
            Element obj_elem = doc.createElement("Object");
            obj_elem.setAttribute("type","LineObject");
            Node obj_node = kvs_node.appendChild( obj_elem );

            // <LineObject>
            Element line_elem = doc.createElement("LineObject");
            line_elem.setAttribute("line_type",m_line_type);
            line_elem.setAttribute("color_type",m_color_type);
            Node line_node = obj_node.appendChild( line_elem );

            // <Vertex nvertices="xxx">
            Element vertex_elem = doc.createElement("Vertex");
            vertex_elem.setAttribute("nvertices", Integer.toString( m_coords.limit() / 3 ) );
            Node vertex_node = line_node.appendChild( vertex_elem );

            // Writing data type.
            final WritingDataType writing_type = m_writing_type;

            // <Coord>
            if ( m_coords.limit() > 0 )
            {
                Element coord_elem = doc.createElement("Coord");
                Node coord_node = vertex_node.appendChild( coord_elem );
                final File coord_file = TagParser.getDataFilename( m_filename, "coord" );
                if ( !TagParser.composeArray( coord_node, writing_type, m_coords, 3, coord_file ) )
                {
                    throw new KVSException("Cannot compose the data array for <Coord>.");
                }
            }

            // <Color>
            if ( m_colors.limit() > 0 )
            {
                Element color_elem = doc.createElement("Color");
                Node color_node = vertex_node.appendChild( color_elem );
                final File color_file = TagParser.getDataFilename( m_filename, "color" );
                if ( !TagParser.composeArray( color_node, writing_type, m_colors, 3, color_file ) )
                {
                    throw new KVSException("Cannot compose the data array for <Color>.");
                }
            }

            // <Size>
            if ( m_sizes.limit() > 0 )
            {
                Element size_elem = doc.createElement("Size");
                Node size_node = vertex_node.appendChild( size_elem );
                final File size_file = TagParser.getDataFilename( m_filename, "size" );
                if ( !TagParser.composeArray( size_node, writing_type, m_sizes, 1, size_file ) )
                {
                    throw new KVSException("Cannot compose the data array for <Size>.");
                }
            }

            // <Line>
            Element line_connect_elem = doc.createElement("Line");
            final int nlines = m_line_type.equals( "uniline" ) ? m_connections.limit() : m_connections.limit() / 2;
            line_connect_elem.setAttribute("nlines", Integer.toString( nlines ) );
            Node line_connect_node = line_node.appendChild( line_connect_elem );

            // <Connection>
            if ( m_connections.limit() > 0 )
            {
                Element connect_elem = doc.createElement("Connection");
                Node connect_node = line_connect_node.appendChild( connect_elem );
                final File connect_file = TagParser.getDataFilename( m_filename, "connect" );
                if ( !TagParser.composeArray( connect_node, writing_type, m_connections, 1, connect_file ) )
                {
                    throw new KVSException("Cannot compose the data array for <Connection>.");
                }
            }

            TransformerFactory tfactory = TransformerFactory.newInstance(); 
            Transformer transformer = tfactory.newTransformer(); 
            transformer.transform( new DOMSource( doc ), new StreamResult (m_filename ) ); 
        } catch (ParserConfigurationException e) {
            e.printStackTrace();
            throw new KVSException("create document failured");
        } catch (TransformerException e) {
            e.printStackTrace();
            throw new KVSException("file write failured");

        }
    }

}
