package kvs.core.fileformat.kvsml;

import java.io.File;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.FloatBuffer;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;

import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.xml.sax.SAXException;

import kvs.core.KVSException;
import kvs.core.fileformat.FileFormatBase;
import kvs.core.fileformat.kvsml.TagParser.WritingDataType;

public class KVSMLObjectPoint extends FileFormatBase {
    
    private static final long serialVersionUID = 6490118884540310289L;
    protected WritingDataType   m_writing_type; ///< writing data type
    protected FloatBuffer       m_coords;  ///< coordinate array
    protected ByteBuffer        m_colors;  ///< color(r,g,b) array
    protected FloatBuffer       m_normals; ///< normal array
    protected FloatBuffer       m_sizes;   ///< size array
    
    public KVSMLObjectPoint(){
        m_writing_type = WritingDataType.Ascii;
    }
    
    public KVSMLObjectPoint( File filename ) throws KVSException{
        m_writing_type = WritingDataType.Ascii;
        this.read( filename );
    }
    
    public FloatBuffer coords()
    {
        return m_coords;
    }
    
    public ByteBuffer colors() 
    {
        return( m_colors );
    }

    public FloatBuffer normals() 
    {
        return( m_normals );
    }

    public FloatBuffer sizes() 
    {
        return( m_sizes );
    }

    public void setWritingDataType( WritingDataType writing_type )
    {
        m_writing_type = writing_type;
    }

    public void setCoords( FloatBuffer coords )
    {
        m_coords = coords;
    }

    public void setColors( ByteBuffer colors )
    {
        m_colors = colors;
    }

    public void setNormals( FloatBuffer normals )
    {
        m_normals = normals;
    }

    public void setSizes( FloatBuffer sizes )
    {
        m_sizes = sizes;
    }

    public static boolean check( File filename )
    {        
        try {
            DocumentBuilderFactory dbfactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder builder = dbfactory.newDocumentBuilder();
            Document document = builder.parse( filename );
            return PointObjectParser.check( document );
        } catch (SAXException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
        catch (ParserConfigurationException e) {
            e.printStackTrace();
        }
        return false;
    }

    @Override
    public void read( File filename ) throws KVSException {
        m_filename = filename;
        try{

            DocumentBuilderFactory dbfactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder builder = dbfactory.newDocumentBuilder();
            Document document = builder.parse( filename );

            PointObjectParser parser =new PointObjectParser();
            parser.parse( document );
            
            TagParser.setCurrentFile( filename );

            m_coords = parser.setCoordsTo();
            m_colors = parser.setColorsTo();
            m_normals = parser.setNormalsTo();
            m_sizes = parser.setSizesTo();

        } catch (SAXException e) {
            e.printStackTrace();
            throw new KVSException("Xml parse failured");
        } catch (IOException e) {
            e.printStackTrace();
            throw new KVSException("Read failured");
        } catch (ParserConfigurationException e) {
            e.printStackTrace();
            throw new KVSException("Create DocumentBuilder failured");
        }
    }

    @Override
    public void write( File filename ) throws KVSException {
        m_filename = filename;
        try{

            DocumentBuilderFactory dbfactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder builder = dbfactory.newDocumentBuilder();

            Document doc = builder.newDocument();

            doc.setXmlVersion( "1.0" );
            doc.createComment( " Generated by kvs.KVSMLObjectLine.write() " );

            // <KVSML>
            Element kvs_node = doc.createElement( "KVSML" );
            doc.appendChild( kvs_node );

            // <Object type="PointObject">
            Element obj_elem = doc.createElement("Object");
            obj_elem.setAttribute("type","PointObject");
            Node obj_node = kvs_node.appendChild( obj_elem );

            // <PointObject>
            Element point_elem = doc.createElement("PointObject");
            Node point_node = obj_node.appendChild( point_elem );

            // <Vertex nvertices="xxx">
            Element vertex_elem = doc.createElement("Vertex");
            vertex_elem.setAttribute("nvertices", Integer.toString( m_coords.limit() / 3 ) );
            Node vertex_node = point_node.appendChild( vertex_elem );
            
            

            // Writing data type.
            final WritingDataType writing_type = m_writing_type;

            // <Coord>
            if ( m_coords.limit() > 0 )
            {
                Element coord_elem = doc.createElement("Coord");
                Node coord_node = vertex_node.appendChild( coord_elem );
                final File coord_file = TagParser.getDataFilename( m_filename, "coord" );
                if ( !TagParser.composeArray( coord_node, writing_type, m_coords, 3, coord_file ) )
                {
                    throw new KVSException("Cannot compose the data array for <Coord>.");
                }
            }

            // <Color>
            if ( m_colors.limit() > 0 )
            {
                Element color_elem = doc.createElement("Color");
                Node color_node = vertex_node.appendChild( color_elem );
                final File color_file = TagParser.getDataFilename( m_filename, "color" );
                if ( !TagParser.composeArray( color_node, writing_type, m_colors, 3, color_file ) )
                {
                    throw new KVSException("Cannot compose the data array for <Color>.");
                }
            }
            
         // <Normal>
            if ( m_normals.limit() > 0 )
            {
                Element normal_elem = doc.createElement("Normal");
                Node normal_node = vertex_node.appendChild( normal_elem );
                final File normal_file = TagParser.getDataFilename( m_filename, "normal" );
                if ( !TagParser.composeArray( normal_node, writing_type, m_normals, 3, normal_file ) )
                {
                    throw new KVSException("Cannot compose the data array for <Normal>.");
                }
            }

            // <Size>
            if ( m_sizes.limit() > 0 )
            {
                Element size_elem = doc.createElement("Size");
                Node size_node = vertex_node.appendChild( size_elem );
                final File size_file = TagParser.getDataFilename( m_filename, "size" );
                if ( !TagParser.composeArray( size_node, writing_type, m_sizes, 1, size_file ) )
                {
                    throw new KVSException("Cannot compose the data array for <Size>.");
                }
            }

            TransformerFactory tfactory = TransformerFactory.newInstance(); 
            Transformer transformer = tfactory.newTransformer(); 
            transformer.transform( new DOMSource( doc ), new StreamResult (m_filename ) ); 
        } catch (ParserConfigurationException e) {
            e.printStackTrace();
            throw new KVSException("create document failured");
        } catch (TransformerException e) {
            e.printStackTrace();
            throw new KVSException("file write failured");

        }
    }

}
